### ISSUE TITLE
ทดลองใช้ markdown

### ISSUE THREAD

**Issue by afterprojectz** [afterprojectz/HelloTest#3]
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)

**Comment by afterprojectz** [comment]
# This is an <h1> tag
## This is an <h2> tag
###### This is an <h6> tag

**Comment by tanawatball** [comment]
กินข้าวมันไก่ก่อน

**Comment by afterprojectz** [comment]
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_
